apiVersion: v2
name: fleet-webui
description: A web console for Rancher Fleet Bundle and GitRepo status
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - rancher
  - fleet
  - gitops
  - kubernetes
home: https://github.com/yxwuxuanl/fleet-webui
sources:
  - https://github.com/yxwuxuanl/fleet-webui
